"use strict";
// Isolated illustrative data: never populate this adapter with watch selection probabilities.
window.PRODUCT_PREVIEW = {
  schema: "pitch_studio_product_preview_v1",
  source_kind: "illustrative",
  model_connected: false,
  causal_attribution: false,
  class_order: [
    "ball",
    "strike",
    "foul",
    "out",
    "single",
    "double",
    "triple",
    "home_run",
    "hbp",
    "double_play",
  ],
  labels: {
    ball: "볼",
    strike: "스트라이크",
    foul: "파울",
    out: "아웃",
    single: "단타",
    double: "2루타",
    triple: "3루타",
    home_run: "홈런",
    hbp: "몸에 맞는 공",
    double_play: "병살",
  },
  scenarios: {
    execution: {
      pitch_type: "SL",
      pitch_label: "슬라이더",
      zone: 7,
      zone_label: "바깥쪽 낮은 코스",
      choices: [
        { code: "SL", label: "슬라이더", share: 58 },
        { code: "SI", label: "싱커", share: 27 },
        { code: "CH", label: "체인지업", share: 15 },
      ],
      probabilities: {
        ball: 0.28,
        strike: 0.27,
        foul: 0.18,
        out: 0.12,
        single: 0.07,
        double: 0.03,
        triple: 0.005,
        home_run: 0.02,
        hbp: 0.01,
        double_play: 0.015,
      },
      command_score: 54,
      contact_score: 82,
      keep: 51.8,
      replace: 54.2,
      pitcher: "제구 이탈 가능성",
      batter: "장타로 연결한 대응",
      manager: "교체 대안 우세",
      pre: "바깥쪽 낮은 슬라이더로 승부합니다.",
      post: "목표보다 가운데에 몰린 공입니다.",
      post_text:
        "목표를 벗어난 공이 장타로 이어진 상황을 가정했습니다. 투구 선택과 실제 실행을 분리해 볼 수 있습니다.",
      batter_text:
        "타자가 실투를 놓치지 않고 강한 타구로 연결한 상황을 가정한 화면입니다.",
      manager_text:
        "교체 후보가 준비되어 있고 유지보다 전망이 나은 상황을 가정했습니다. 교체하지 않은 선택을 검토할 근거를 보여줍니다.",
    },
    batter: {
      pitch_type: "SI",
      pitch_label: "싱커",
      zone: 9,
      zone_label: "몸쪽 낮은 코스",
      choices: [
        { code: "SI", label: "싱커", share: 61 },
        { code: "SL", label: "슬라이더", share: 24 },
        { code: "CH", label: "체인지업", share: 15 },
      ],
      probabilities: {
        ball: 0.24,
        strike: 0.31,
        foul: 0.2,
        out: 0.14,
        single: 0.05,
        double: 0.02,
        triple: 0.003,
        home_run: 0.012,
        hbp: 0.01,
        double_play: 0.015,
      },
      command_score: 91,
      contact_score: 94,
      keep: 55.1,
      replace: 54.4,
      pitcher: "목표대로 수행",
      batter: "좋은 공을 공략",
      manager: "현재 투수 유지",
      pre: "몸쪽 낮은 싱커로 타이밍을 흔듭니다.",
      post: "목표는 지켰지만, 타자가 대응했습니다.",
      post_text:
        "요구 위치에 가까이 던진 공을 타자가 잘 공략한 상황입니다. 안타를 허용했다는 사실만으로 제구 실패로 분류하지 않는 화면입니다.",
      batter_text:
        "불리한 코스에 온 공을 강하게 맞힌 상황을 가정했습니다. 타격의 질과 안타·아웃 결과를 구분합니다.",
      manager_text:
        "현재 투수를 유지하는 전망이 교체 대안보다 소폭 높은 상황입니다. 이후 안타가 나와도 당시 선택의 근거를 다시 확인할 수 있습니다.",
    },
    manager: {
      pitch_type: "CH",
      pitch_label: "체인지업",
      zone: 8,
      zone_label: "낮은 코스",
      choices: [
        { code: "CH", label: "체인지업", share: 46 },
        { code: "SL", label: "슬라이더", share: 34 },
        { code: "SI", label: "싱커", share: 20 },
      ],
      probabilities: {
        ball: 0.32,
        strike: 0.22,
        foul: 0.17,
        out: 0.13,
        single: 0.08,
        double: 0.035,
        triple: 0.005,
        home_run: 0.025,
        hbp: 0.01,
        double_play: 0.005,
      },
      command_score: 67,
      contact_score: 79,
      keep: 48.6,
      replace: 53.7,
      pitcher: "제구 안정성 점검",
      batter: "유리한 매치업",
      manager: "교체 검토 필요",
      pre: "타이밍을 바꾸는 선택을 비교합니다.",
      post: "같은 선택을 이어가도 괜찮을까요.",
      post_text:
        "구위·제구 변화와 다음 타순을 함께 살펴봐야 하는 상황을 가정했습니다.",
      batter_text:
        "타순의 강점과 현재 투수의 공이 맞물리는 상황을 가정한 평가 화면입니다.",
      manager_text:
        "불펜 후보가 가용하고 교체 전망이 우세한 상황입니다. 유지·교체의 기대 결과와 당시 가용 정보를 나란히 놓습니다.",
    },
    missed: {
      pitch_type: "SI",
      pitch_label: "싱커",
      zone: 5,
      zone_label: "가운데 코스",
      choices: [
        { code: "SI", label: "싱커", share: 48 },
        { code: "SL", label: "슬라이더", share: 32 },
        { code: "CH", label: "체인지업", share: 20 },
      ],
      probabilities: {
        ball: 0.22,
        strike: 0.23,
        foul: 0.18,
        out: 0.13,
        single: 0.12,
        double: 0.05,
        triple: 0.005,
        home_run: 0.035,
        hbp: 0.01,
        double_play: 0.02,
      },
      command_score: 49,
      contact_score: 38,
      keep: 52.4,
      replace: 52.1,
      pitcher: "실투였지만 아웃",
      batter: "기회를 살리지 못한 대응",
      manager: "유지·교체 전망 유사",
      pre: "타자가 노릴 수 있는 코스입니다.",
      post: "아웃을 잡았어도 실행은 돌아봅니다.",
      post_text:
        "공이 가운데에 몰렸지만 약한 타구로 아웃을 잡은 상황입니다. 좋은 결과만으로 좋은 제구였다고 평가하지 않는 예시입니다.",
      batter_text:
        "유리한 공에 타이밍이 늦어 약한 타구가 나온 상황입니다. 아웃이라는 결과와 공략 기회를 놓친 대응을 함께 보여주는 예시입니다.",
      manager_text:
        "유지와 교체의 전망이 비슷한 상황입니다. 한 구의 결과만으로 교체가 정답이었다고 단정하지 않는 화면입니다.",
    },
  },
};
